version: '3.7'
services:
  bot:
    image: ha-whatsapp-bot-bot:latest
    restart: on-failure
    environment:
      - WHATSAPP_API_TOKEN=${WHATSAPP_API_TOKEN}
      - WHATSAPP_PHONE_NUMBER_ID=${WHATSAPP_PHONE_NUMBER_ID}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - WEBHOOK_VERIFY_TOKEN=${WEBHOOK_VERIFY_TOKEN}
      - HOME_ASSISTANT_URL=${HOME_ASSISTANT_URL}
      - HOME_ASSISTANT_TOKEN=${HOME_ASSISTANT_TOKEN}
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
