version: '3.7'
services:
  bot:
    image: ha-whatsapp-bot-bot:latest
    restart: on-failure
    environment:
      - HA_URL=${HA_URL}
      - HA_TOKEN=${HA_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ${APP_DATA_DIR}/auth_info_baileys:/app/auth_info_baileys
