version: '3.7'

services:
  app_proxy:
    environment:
      # Hier sagen wir Umbrel, wo das Webinterface läuft: 
      # nämlich bei unserem "server" (Übersetzer) auf Port 8081.
      APP_HOST: niklas-cameraui_server_1
      APP_PORT: 8081

  app:
    image: ghcr.io/cameraui/camera.ui:latest
    restart: on-failure
    network_mode: "host"
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ${APP_DATA_DIR}/data:/data
  server:
    # Dieser Hilfs-Container fungiert als "Übersetzer" zwischen Umbrel und Camera.UI.
    # Umbrel spricht nur normales HTTP (über Port 8081), Camera.UI verlangt aber HTTPS (auf Port 3443).
    image: alpine/socat
    restart: on-failure
    command: tcp-listen:8081,fork,reuseaddr openssl-connect:192.168.1.2:3443,verify=0
